In [67]:
import numpy as np
import pandas as pd

In [68]:
df= pd.read_csv("data.csv")

In [69]:
df

country   Age Salary Purchased
0       a  45.0    78k        no
1       b  28.0    48k       yes
2       c  30.0    54k        no
3       b  38.0    61k        no
4       a  40.0    NaN       yes
5       d  35.0    58k       yes
6       c   NaN    53k        no
7       b  48.0    79k       yes
8       a  50.0    83k        no
9       b  37.0    67k       yes

# identifying the dependent and independent variable 
in above case the purchase is the independent varible and the country,age, and the salary are the dependet variable

In [70]:
#dependent variable

x= df[['country','Age','Salary']]
x['Salary']=x['Salary'].str.replace('k','000')
x=x.values
x

C:\Users\Anand\AppData\Local\Temp\ipykernel_16592\1377186064.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['Salary']=x['Salary'].str.replace('k','000')


array([['a', 45.0, '78000'],
       ['b', 28.0, '48000'],
       ['c', 30.0, '54000'],
       ['b', 38.0, '61000'],
       ['a', 40.0, nan],
       ['d', 35.0, '58000'],
       ['c', nan, '53000'],
       ['b', 48.0, '79000'],
       ['a', 50.0, '83000'],
       ['b', 37.0, '67000']], dtype=object)

In [71]:
#independent varible
y =df[['Purchased']].values
y

array([['no'],
       ['yes'],
       ['no'],
       ['no'],
       ['yes'],
       ['yes'],
       ['no'],
       ['yes'],
       ['no'],
       ['yes']], dtype=object)

# Handling the missing value
two ways.

1.drop the missing value if it contains more than 70% of the data set.

2.replace the value with median  of the mode.

In [72]:
from sklearn.impute import SimpleImputer

first method

In [73]:
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')

In [74]:
imputer=imputer.fit(x[:,1:3])

In [75]:
#replacinng the values with the mean
x[:,1:3]= imputer.transform(x[:,1:3])
x

array([['a', 45.0, 78000.0],
       ['b', 28.0, 48000.0],
       ['c', 30.0, 54000.0],
       ['b', 38.0, 61000.0],
       ['a', 40.0, 64555.555555555555],
       ['d', 35.0, 58000.0],
       ['c', 39.0, 53000.0],
       ['b', 48.0, 79000.0],
       ['a', 50.0, 83000.0],
       ['b', 37.0, 67000.0]], dtype=object)

# converting the categorical data into the numerica value
because most of the machine learning algorithm can not work with the categorical data, so we have to assign some numerical values to the city columns

for that we have different libraries

In [76]:
from sklearn.preprocessing import LabelEncoder

In [77]:
labelencoder_x=LabelEncoder()

In [78]:
#converting the city column and storing it into the x
x[:,0]=labelencoder_x.fit_transform(x[:,0]) 
x


array([[0, 45.0, 78000.0],
       [1, 28.0, 48000.0],
       [2, 30.0, 54000.0],
       [1, 38.0, 61000.0],
       [0, 40.0, 64555.555555555555],
       [3, 35.0, 58000.0],
       [2, 39.0, 53000.0],
       [1, 48.0, 79000.0],
       [0, 50.0, 83000.0],
       [1, 37.0, 67000.0]], dtype=object)

# dummy encoding
here we converted cities into a numeric value but since its a numeric value then the algo might think that the a is the smallest city because it has 

the list parameter where as the city value with 3 is the largest city because it has the largest value.

so we have to do the dummy encoding. so it is a prcess in which we assign the each city a separte column and if the firsr row belong to that city then in that row of the city the value would
be 1 while other city value would be zero


In [79]:
from sklearn.preprocessing import OneHotEncoder

In [80]:
onehotencoder= OneHotEncoder()

In [81]:
x=onehotencoder.fit_transform(df.country.values.reshape(-1,1)).toarray()

In [82]:
labelencoder_y =LabelEncoder()
y= labelencoder_y.fit_transform(y)

c:\Users\Anand\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\preprocessing\_label.py:115: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [83]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# data Split data_train/ data_test
some data use for training the algorithm while

some data set is use for the testing the algorithm

In [84]:
from sklearn.model_selection import train_test_split

In [85]:
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.2, random_state =0) #0.2 means you are testing 20% of your data

In [86]:
x_train

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [87]:
x_test

array([[0., 0., 1., 0.],
       [1., 0., 0., 0.]])

In [89]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [90]:
y_test

array([0, 0])

# feature scaling
there might be some feature in the data set which might vary alot that's why we need the feature cleaning

In [91]:
from sklearn.preprocessing import StandardScaler

In [92]:
sc_x= StandardScaler()

In [97]:
x_train=sc_x.fit_transform(x_train)
x_train

array([[ 1.73205081, -1.        , -0.37796447, -0.37796447],
       [-0.57735027,  1.        , -0.37796447, -0.37796447],
       [-0.57735027,  1.        , -0.37796447, -0.37796447],
       [-0.57735027, -1.        ,  2.64575131, -0.37796447],
       [-0.57735027,  1.        , -0.37796447, -0.37796447],
       [-0.57735027,  1.        , -0.37796447, -0.37796447],
       [ 1.73205081, -1.        , -0.37796447, -0.37796447],
       [-0.57735027, -1.        , -0.37796447,  2.64575131]])

In [95]:
x_test= sc_x.fit_transform(x_test)

Now our data is ready for the visualistion